name: Create tag
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get tag info
        id: tag_info
        uses: andstor/file-reader-action@v1
        with:
          path: "VERSION"
      - name: Create tag
        uses: tvdias/github-tagger@v0.0.1
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          tag: "${ steps.tag_info.outputs.contents }"
